import Head from 'next/head'

import GsapTest from '../components/gsap-test';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>

        <GsapTest />
      </main>

    </div>
  )
}
